version: "3"
services:
  db:
    image: "postgres:12"
    container_name: "commanded_shareback_db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=code_example_test
    volumes:
      - /var/lib/postgresql/data
